# Generated by Django 3.0.5 on 2020-04-23 17:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(default='strzecho', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('repetitions', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Training'),
        ),
    ]
