# Generated by Django 3.0.5 on 2020-06-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200623_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='user',
        ),
    ]
