# Generated by Django 3.0.5 on 2020-06-23 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_remove_training_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
    ]
